export const TEXT = {
  EN: {
    CAPTION_PLACEHOLDER: 'Add your description',
    COMMENT_PLACEHOLDER: 'Enter comment ...',
    EDITOR_PLACEHOLDER: 'Enter content ...',
    EMBED_CODE_PLACEHOLDER: 'Paste JSFiddle and press enter',
    EMBED_VIDEO_PLACEHOLDER: 'Paste YouTube or Vimeo link, and press enter',
    LINK_PLACEHOLDER: 'Enter link',
    LIKE_BUTTON_FAILED:
      "Like button has been embeded, so you don't need to another.",
    TITLE_FALLBACK: 'Untitle',
    TITLE_PLACEHOLDER: 'Enter title ...',
    TOOLBAR_ADD_DIVIDER: 'Add divivder',
    TOOLBAR_ADD_IMAGE: 'Add image',
    TOOLBAR_CLOSE: 'Close toolbar',
    TOOLBAR_EMBED_CODE: 'Embed code snippet',
    TOOLBAR_EMBED_AUDIO: 'Embed audio',
    TOOLBAR_EMBED_VIDEO: 'Embed video',
    TOOLBAR_OPEN: 'Open toolbar',
    UPLOAD_AUDIO_FAILED: 'Audio upload failed',
    UPLOAD_AUDIO_REACH_SIZE_LIMIT: 'Image size must be under 100MB',
    UPLOAD_AUDIO_SUCCESSFUL: 'Audio upload successfully',
    UPLOAD_AUDIO_TOOLTIP:
      'Only accept MP3 and AAC, and size must be under 100MB',
    UPLOAD_IMAGE_FAILED: 'Image upload failed',
    UPLOAD_IMAGE_REACH_SIZE_LIMIT: 'Image size must be under 5MB',
    UPLOAD_IMAGE_SINGLE_LIMIT: 'Please upload one image at a time',
    UPLOAD_IMAGE_SUCCESSFUL: 'Image upload successfully',
  },
  ZH_HANS: {
    CAPTION_PLACEHOLDER: '添加说明文字…',
    COMMENT_PLACEHOLDER: '发表你的评论…',
    EDITOR_PLACEHOLDER: '请输入正文…',
    EMBED_CODE_PLACEHOLDER: '贴上 JSFiddle 链接後，Enter 进行新增',
    EMBED_VIDEO_PLACEHOLDER: '贴上 YouTube、Vimeo 链接後，Enter 进行新增',
    LINK_PLACEHOLDER: '输入链接地址',
    LIKE_BUTTON_FAILED: '作品页面中的赞赏按钮已嵌入 LikeButton，你无需手动添加',
    TITLE_FALLBACK: '未命名',
    TITLE_PLACEHOLDER: '请输入标题…',
    TOOLBAR_ADD_DIVIDER: '新增分割线',
    TOOLBAR_ADD_IMAGE: '新增圖片',
    TOOLBAR_CLOSE: '收起工具栏',
    TOOLBAR_EMBED_AUDIO: '新增音頻',
    TOOLBAR_EMBED_CODE: '新增代碼链接',
    TOOLBAR_EMBED_VIDEO: '新增视频',
    TOOLBAR_OPEN: '展开工具栏',
    UPLOAD_AUDIO_FAILED: '音频上传失败',
    UPLOAD_AUDIO_REACH_SIZE_LIMIT: '上传文件请勿超过 100 MB',
    UPLOAD_AUDIO_SUCCESSFUL: '音频上传成功',
    UPLOAD_AUDIO_TOOLTIP: 'MP3 或 AAC 格式，不超过 100 MB',
    UPLOAD_IMAGE_FAILED: '圖片上傳失敗',
    UPLOAD_IMAGE_REACH_SIZE_LIMIT: '上传文件请勿超过 5 MB',
    UPLOAD_IMAGE_SINGLE_LIMIT: '请一次上传一个文件',
    UPLOAD_IMAGE_SUCCESSFUL: '圖片上傳成功',
  },
  ZH_HANT: {
    CAPTION_PLACEHOLDER: '添加說明文字…',
    COMMENT_PLACEHOLDER: '發表你的評論…',
    EDITOR_PLACEHOLDER: '請輸入正文…',
    EMBED_CODE_PLACEHOLDER: '貼上 JSFiddle 連結後，Enter 進行新增',
    EMBED_VIDEO_PLACEHOLDER: '貼上 YouTube、Vimeo 連結後，Enter 進行新增',
    LINK_PLACEHOLDER: '輸入連結地址',
    LIKE_BUTTON_FAILED: '作品頁面中的讚賞按鈕已嵌入 LikeButton，你無需手動添加',
    TITLE_FALLBACK: '未命名',
    TITLE_PLACEHOLDER: '請輸入標題…',
    TOOLBAR_ADD_DIVIDER: '新增分割線',
    TOOLBAR_ADD_IMAGE: '新增圖片',
    TOOLBAR_CLOSE: '收起工具欄',
    TOOLBAR_EMBED_AUDIO: '新增音訊',
    TOOLBAR_EMBED_CODE: '新增程式碼連結',
    TOOLBAR_EMBED_VIDEO: '新增影片',
    TOOLBAR_OPEN: '展開工具欄',
    UPLOAD_AUDIO_FAILED: '音訊上傳失敗',
    UPLOAD_AUDIO_REACH_SIZE_LIMIT: '上傳檔案請勿超過 100 MB',
    UPLOAD_AUDIO_SUCCESSFUL: '音訊上傳成功',
    UPLOAD_AUDIO_TOOLTIP: 'MP3 或 AAC 格式，不超過 100 MB',
    UPLOAD_IMAGE_FAILED: '圖片上傳失敗',
    UPLOAD_IMAGE_REACH_SIZE_LIMIT: '上傳檔案請勿超過 5 MB',
    UPLOAD_IMAGE_SINGLE_LIMIT: '請一次上傳一個檔案',
    UPLOAD_IMAGE_SUCCESSFUL: '圖片上傳成功',
  },
}
